development:
  adapter: postgresql
  host: localhost
  database: vanwilder_development
  pool: 16
  timeout: 5000
  username:

test:
  adapter: postgresql
  host: localhost
  database: vanwilder_test
  pool: 16
  timeout: 5000
  username:
